[package]
name = "rpls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.18", features = ["derive"] }
csv = "1.1.6"
float-ord = "0.3.2"
geo = "0.23.0"
plotters = "0.3.3"
